version: "3"

services:
  webserver:
    container_name: cricket-stats-webserver
    build:
      context: ./build
      dockerfile: Dockerfile
    image: cricket-server:0.2
    ports:
      - "8081:80/tcp"
    restart: unless-stopped
